= Ci Kang - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: JobbiBot

---

== Overview

JobbiBot is an interactive application that aims to guide university students in their search for internships. JobbiBot is a Command
Line Interface application where most of the functions are accessed through typing the commands. Through JobbiBot,
users would be able to narrow down the overwhelming amount of internship opportunities by different attributes such as salary and industry with
the help of JobbiBot which will guide the user slowly through the process with prompts and useful tips.
Afterwhich they can either save the list of internships while making the decision, select the internship and obtain comprehensive details about
the internship or they may restart the process and filter the internships differently.

== Summary of contributions

* *Major enhancement*: modified the find function *to enable user to do a distinct union search*
** What it does: Allows users to search for multiple keywords and all internships containing ANY of the keywords will be listed.
the internship in the list are then tagged with tags containing keywords which it matches.
** Justification: This feature improves the product significantly because a user can narrow down their internships opportunities
yet at the same time keep their options open by selecting multiple keywords to search for.

** Highlights: Enable the search of multiple keywords in all the attributes of the internships and can repeat the find command indefinitely until
a suitable list of internships are obtained for further filtering.

* *Minor enhancement*: Modified the preview list on the left to show important attributes and full details on the right panel if internship is selected.

* *Code contributed*: [https://github.com/CS2103JAN2018-F11-B3/main/blob/master/collated/functional/TanCiKang.md[Functional Code]]
 [https://github.com[Test code]]

* *Other contributions*:

** Project management:
*** Managed release `v1.3` on GitHub
** Enhancements to existing features:
*** Implemented Role https://github.com/CS2103JAN2018-F11-B3/main/issues/54[#52], Salary https://github.com/CS2103JAN2018-F11-B3/main/issues/64[#64], Industry https://github.com/CS2103JAN2018-F11-B3/main/issues/66[#66] and Region https://github.com/CS2103JAN2018-F11-B3/main/issues/67[#67] attributes
*** Morph Person Class to Internship Class https://github.com/CS2103JAN2018-F11-B3/main/issues/65[#65]
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Collate codes for team https://github.com/CS2103JAN2018-F11-B3/main/pull/102[#102]
*** Setting up of Travis Auto Publishing for the team

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=findwithfeature]

//include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=findwithfeatures]

//include::../DeveloperGuide.adoc[]


---

_{Optionally, you may include other projects in your portfolio.}_
